name: 'scd2_registry'
version: '1.0.0'
config-version: 2

profile: 'scd2_registry'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  scd2_registry:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
